spring:
  application:
    name: anttu.code.github.io
  # spring内置json的日期转换配置
  jackson.date-format: yyyy-MM-dd HH:mm:ss

  # 环境 dev:开发环境|test:测试环境|prod:生产环境|home:家里的ip
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 11QQaazz
    hikari:
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 4
      # 最大连接数
      maximum-pool-size: 10
      # 是否自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒）
      idle-timeout: 30000
      # 连接池名称
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒）
      max-lifetime: 1800000
      # 连接测试sql
      connection-test-query: SELECT 1
  redis:
    database: 0
    port: 6379
    password: 11QQaazz
    # 链接超时时间
    timeout: 5000
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
      shutdown-timeout: 100
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAdterWrite=60s

mybatis:
  mapperLocations: classpath:mapper/*.xml

server:
  tomcat:
    basedir: ./tmp
  port: 8090

#全局密钥配置，所以加密算法统一密钥
api:
  encrypt:
    key: d7b85c6e414dbcda
#此配置的公司钥信息为测试数据，不能直接使用，请自行重新生成公私钥
rsa:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq8opPmIi8+lFo4Rx4bD50yj50TA/y4XxKlA0pyGXAJFnfqadoOr3c+H7GfWbJcdSdWDsq3L4s8+G/Tv3byHtmV7ph4aWiUTWJ2vbq9PY2tq1HKiELT/oLnf5T7oWyGdKOfki9iJ0pE+zA3DDa6PyMOOum+DHYW0HhfpASd6QUaTmqx+PyXWSYOxBzWXrRAhcFqMP6AklaCMAlmAmVtjegzHtkFbzAFHwTiwEwR7ib0mEfIJFZdiX1Ymp2RFm2UC3aaNovB6GZaFY73Hefqk9D8KKRkKlUszSqP+Sc2ux9Q5ZP7NUzwmBZnuxDpMermALk6j3xTdpMPKxy2+9EsdfkQIDAQAB
  privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJxmWQdpI3R/DcJYaDNy4944o900od1zadHootdrOGHMWF7vw2oyuGzI1N/frmxoVLaUAMrcLMBLMfhPRtP4acnvuOgM4/7RKq5scrAAi/znSVPRDFL5165QeDb64diF2EjDk0KZnRKQ1qXDyKA/XJL7ZMQhhqfeVqQ8G9khKpGzAgMBAAECgYEAj+5AkGlZj6Q9bVUez/ozahaF9tSxAbNs9xg4hDbQNHByAyxzkhALWVGZVk3rnyiEjWG3OPlW1cBdxD5w2DIMZ6oeyNPA4nehYrf42duk6AI//vd3GsdJa6Dtf2has1R+0uFrq9MRhfRunAf0w6Z9zNbiPNSd9VzKjjSvcX7OTsECQQD20kekMToC6LZaZPr1p05TLUTzXHvTcCllSeXWLsjVyn0AAME17FJRcL9VXQuSUK7PQ5Lf5+OpjrCRYsIvuZg9AkEAojdC6k3SqGnbtftLfGHMDn1fe0nTJmL05emwXgJvwToUBdytvgbTtqs0MsnuaOxMIMrBtpbhS6JiB5Idb7GArwJAfKTkmP5jFWT/8dZdBgFfhJGv6FYkEjrqLMSM1QT7VzvStFWtPNYDHC2b8jfyyAkGvpSZb4ljZxUwBbuh5QgM4QJBAJDrV7+lOP62W9APqdd8M2X6gbPON3JC09EW3jaObLKupTa7eQicZsX5249IMdLQ0A43tanez3XXo0ZqNhwT8wcCQQDUubpNLwgAwN2X7kW1btQtvZW47o9CbCv+zFKJYms5WLrVpotjkrCgPeuloDAjxeHNARX8ZTVDxls6KrjLH3lT
